### PR TITLE
Show description when backslash key is pressed

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Added an option for displaying description when backslash key is pressed during 10 minute mode.

This was really just a feature I wanted for myself. Often, I'd like to see the location after I've not been paying attention to my computer for a while. I am not sure if this is a feature useful for the main project, but I decided to make a PR in case the feature is interesting for others.

I am new to Swift and macOS development, so let me know if there are things I can improve.

### CODE REVIEW

**Comment by glouel** [comment]
Hi @nalinbhardwaj !

First, apologies for not answering sooner. Also, thanks a lot for sharing your contribution, this is not the easiest project to get into (lots of old code, many quick hacks on top of quick hacks) so props to you for doing it as your first swift project !

This feature has been requested a few times so it's a great idea to implement it and I think it definitely has it's place in Aerial. 

I probably won't be able to have a good look at your code until tomorrow or wednesday, so again apologies for that, but some general remarks about the idea:

- I think maybe the key should be configurable ? Backslash isn't a key on a french keyboard to give you an example. Some people suggested using the space bar for this, or gently tapping the touchpad (ala Apple TV if you've seen one, but that might be a bit overkill). Maybe just a popup with multiple choices of keys to pick from ? Or a field where one can input it's favorite key for this (with a sensible default that works everywhere, maybe something like "tab" ?)

- There are some boundaries things to account for but a quick look makes me think you thought of them (what if I press the key 5 sec before a new description is supposed to pop). Also, make sure you correctly handle the various corners settings, etc

All in all, this looks awesome and I'll merge it as soon as as I can have a good look at it. And if in the meantime you have ideas about configuring the key to use, let me know.

Thanks again for sharing!

**Comment by nalinbhardwaj** [comment]
Hi @glouel : 

> I think maybe the key should be configurable ? Backslash isn't a key on a french keyboard to give you an example.

TIL; I'll look into ways of making the key configurable. Are you aware of any projects (open source or otherwise) doing a configurable key selection nicely? A quick search didn't really show any. But yes, a pop up window shouldn't be very hard to do. Although, I think having the user somehow just type their favourite key is better UX. While at it, I think this is a good change for the "right arrow key" prompt on "Videos" page as well.

About the default selection, personally, I think "tab" and "right arrow key" have similar meanings in my mind, and I think users might find it annoying that they do very different things. What do you think about "shift"?

> There are some boundaries things to account for

Yes. I think the only boundary case I don't really handle currently is when text is already being displayed. If \ is pressed then, Aerial just redraws and fades in the same text. It doesn't seem like a hard fix,  I'll update the PR soon.

Having used the PR on my machine for a couple days, I think I'd also like a way to disable showDescription, but still see the text when I press backslash (currently, you must use the 10 sec mode). I'll make a commit to add that to the settings as well.

> I probably won't be able to have a good look at your code until tomorrow or wednesday

No worries, I think I'll need a couple days to do the changes I've mentioned in this comment anyway.

Thank you for maintaining this project. It has been my screensaver for a few years now. <3

**Comment by glouel** [comment]
> TIL; I'll look into ways of making the key configurable. Are you aware of any projects (open source or otherwise) doing a configurable key selection nicely? A quick search didn't really show any.

One example that comes to mind is Xcode, if you select a button (for example the Done button in PreferencesWindow.xib)and look at the attributes inspector (5th icon in the right panel), look for "Key Equivalent". The way this works, you click the text field, and then you can input one key. I have no idea if this is a standard behavior of  or not, if it is, that would be awesome and quick. 

> But yes, a pop up window shouldn't be very hard to do. 

It's the easy out but better than nothing yep !

> Although, I think having the user somehow just type their favourite key is better UX. While at it, I think this is a good change for the "right arrow key" prompt on "Videos" page as well.

Completely agreed, and defintely use the same thing for right arrow !

> About the default selection, personally, I think "tab" and "right arrow key" have similar meanings in my mind, and I think users might find it annoying that they do very different things. What do you think about "shift"?

Indeed for tab. Shift is usually considered a "modifier" key which may be it's own challenge, but yep, if it works, sure (need to handle both sides which are usually separate events)

> > There are some boundaries things to account for
> 
> Yes. I think the only boundary case I don't really handle currently is when text is already being displayed. If \ is pressed then, Aerial just redraws and fades in the same text. It doesn't seem like a hard fix, I'll update the PR soon.

Redrawing on top is fine if that's the only thing, you may have overlapping fades which may look weird but I could live with that. 

> Having used the PR on my machine for a couple days, I think I'd also like a way to disable showDescription, but still see the text when I press backslash (currently, you must use the 10 sec mode). I'll make a commit to add that to the settings as well.

Good idea ! 

> No worries, I think I'll need a couple days to do the changes I've mentioned in this comment anyway.

Take your time, I'll try to have a look tomorrow at key selection to see if there's something in textfields to help us here and get back to you.

> Thank you for maintaining this project. It has been my screensaver for a few years now. <3

Hehe, thanks ! And thanks for working on this, truly appreciated !

**Comment by glouel** [comment]
You might want to have a look at this : https://stackoverflow.com/questions/14790725/key-equivalent-nstextfield-like-interface-builder

Looks like there’s a free cocoa component that  does it all called shortcut recorder which may be a useful thing to look at too !

**Comment by glouel** [comment]
So just some thoughts on the shorcut recoder solutions, if you give them a look, they are a pretty big thing because they try to record both key and modifiers and display that (so Cmd+Shift+S for example, which is why I mentionned shift may be weird above). This is not exactly what we need. 

I think that a very simple solution can be done with a NSTextField (probably need to make a subclass of it):
- Hook the becomesFirstResponder event for that text field (see here : https://stackoverflow.com/questions/25692122/how-to-detect-when-nstextfield-has-the-focus-or-is-its-content-selected-cocoa)
- When that event comes, listen to the next keypress (maybe use the placeholder attribut to put a message like "Type a key" so user knows what to do). To get the keycode, use API in that link : https://stackoverflow.com/questions/14790725/key-equivalent-nstextfield-like-interface-builder
- After you grab the key, resign responder status (so we lose focus on the control), put the keycode (or a representation) in the field (the .stringValue) and boom. Store that keycode in preferences. 

This is not trivial and if you'd rather not do it I would completely understand. Let me know if you'd rather have me do that part, or I can try and guide you if you are stuck, up to you !

**Comment by nalinbhardwaj** [comment]
@glouel : Indeed, it does seem Quartz events are the way to go for listening for the keypress.

> This is not trivial and if you'd rather not do it I would completely understand. Let me know if you'd rather have me do that part, or I can try and guide you if you are stuck, up to you !

I am new to Swift, but I would like to try to do it. Thank you for finding all the threads. I also read a number of resources on this, and I'll try to implement everything soon and see what works best. If I have too much trouble, I'll let you know.

I've also just pushed a commit which makes the old mode and the new mode independent and fixes the bug about redrawing on multiple keypress. Let me know if you have any comments about that part of the interface/functionality.

**Comment by glouel** [comment]
> @glouel : Indeed, it does seem Quartz events are the way to go for listening for the keypress.
> 
> > This is not trivial and if you'd rather not do it I would completely understand. Let me know if you'd rather have me do that part, or I can try and guide you if you are stuck, up to you !
> 
> I am new to Swift, but I would like to try to do it. Thank you for finding all the threads. I also read a number of resources on this, and I'll try to implement everything soon and see what works best. If I have too much trouble, I'll let you know.

Awesome ! Take your time, and if you need a hand for anything, just ask.

> I've also just pushed a commit which makes the old mode and the new mode independent and fixes the bug about redrawing on multiple keypress. Let me know if you have any comments about that part of the interface/functionality.

Here's what I suggest, I'm going to merge this PR as-is and have a look (I may change the default key) so I can test it further. 

In the meantime, you can keep working on the other thing. Sounds good ?

**Comment by nalinbhardwaj** [comment]
@glouel :

> Here's what I suggest, I'm going to merge this PR as-is and have a look (I may change the default key) so I can test it further.

If you prefer that, sure. I'm not sure, but if you're only doing it to be able to checkout/test my PR locally, you can use git to do that without merging my PR. See [this](https://help.github.com/en/articles/checking-out-pull-requests-locally) or [this](https://blog.scottlowe.org/2015/09/04/checking-out-github-pull-requests-locally/). That way, GitHub code review can make it easier to communicate with (using the "Code" tab from the top).

**Comment by glouel** [comment]
Good to know ! I'll do that then. Keep working on this PR then so we merge it all at once. I'll merge locally and let you know if there's anything particular ! Thanks !

**Comment by glouel** [comment]
It's a bit of a mess to test Aerial on Catalina on my system but I finally managed to have a good look. So first, looks like everything work as intended, which is great. We already talked about the backlash key which doesn't exist on my keyboard, but it's the same position physically (so it's the ` key here ;)) when you use keyCodes as you did.

Having it work independently of 10 sec looks good too, and UI wise that's logical enough. 

Couple of things I saw, mostly due to the resizing of the window:
- On most textfields, there's a hidden button with "..." as title next to them. This is a workaround for pre Mojave OSes. On the Text panel, at the bottom, you have one that's no longer properly aligned (it's below the "Same Corner" popup). This one goes next to the extra message text field.
- Updates tab, we have the last checked on at the bottom that's stuck at the bottom. It's position was always weird because it's not really linked to "Look for beta" but maybe at the bottom as it is may not be that much better. 

Code wise, not much to say, this looks logical enough and I think you caught the various issues surrounding that. 

The only thing I saw, but wasn't able to test (control panel doesn't work on catalina) is that I think that if you disable show on, but have the popup next to it on always, this is going to mess up your logic as it will not show for 10secs as one would probably expect ?

Those are tiny things all in all, so keep it up, this is going to be a great addition to Aerial !

**Comment by glouel** [comment]
@nalinbhardwaj just wanted to give you a heads up, right now intercepting keys is no longer possible in Catalina or legacyScreenSavers. I'm unsure if/when it will be possible again so, but thought you should know. More about it in the Catalina issue.

**Pull request closed without merging**
