### PR TITLE
Update to fix some typos

### PR DESCRIPTION
**Pull request by NightRaider73**
Some fixes to make it look nicer:)

### CODE REVIEW

**Comment by NightRaider73** [comment]
@glouel Update typos

**Comment by NightRaider73** [comment]
And deleted The Auto updates section because it is kinda deceiving:)

**Comment by glouel** [comment]
Please remove your changes to the auto update.

**Comment by NightRaider73** [comment]
I am going to rebase:)

**Comment by glouel** [comment]
Thanks!

**Comment by NightRaider73** [comment]
I just finished

**Comment by NightRaider73** [comment]
And I contacted JohnCoates so hopefully he responds:)

**Pull request closed without merging**
