### PR TITLE
Migration to Swift 4 and Xcode 9.1

### PR DESCRIPTION
**Pull request by klaas**
Apple pushes us to keep up with Swift. Since Xcode 9.1 Swift 4 is the one to use. The changes were little, so it would be a good idea to merge this one.

### CODE REVIEW

**Comment by alistairmcmillan** [comment]
I know @klaas is already aware of this, but just for anyone else seeing this. For the moment Swift screensavers compiled with Xcode 9.1 seem to be corrupt. Although it will compile successfully, it just seems to create a screen saver that endlessly displays the "You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver." error.

**Comment by klaas** [comment]
I did a build with Xcode Version 9.2 beta (9C34b) and the result is the same :(

**Comment by esetnik** [comment]
@klaas I'm keeping my fork at swift 3 for now 😢 . I guess we can keep this rebased and merge it in once Apple fixes Xcode 9.

**Comment by mckern** [comment]
Good news! This compiled and works for me in macOS 10.13.3 (Xcode 9.2). But there's a fun UI bug:

screen shot 2018-01-24 at 11 40 50 pm

**Comment by esetnik** [comment]
I already fixed that UI bug in my fork as well, good to know we can now compile it with swift 4.

**Comment by klaas** [comment]
@mckern did you really use Xcode 9.2 and macOS 10.13.3? 

I used the latest versions (Xcode 9.2 9C40b, macOS 10.13.3 17D2047) with my Klaas-Swift4 branch and sadly still get the same error when going to the saver preferences:

`Error loading /Users/klaas/Library/Screen Savers/Aerial.saver/Contents/MacOS/Aerial:  dlopen(/Users/klaas/Library/Screen Savers/Aerial.saver/Contents/MacOS/Aerial, 265): can't resolve symbol _OBJC_CLASS_$_NSError in /Users/klaas/Library/Screen Savers/Aerial.saver/Contents/MacOS/../Frameworks/libswiftCore.dylib because dependent dylib #1 could not be loaded in /Users/klaas/Library/Screen Savers/Aerial.saver/Contents/MacOS/../Frameworks/libswiftCore.dylib`

Maybe you did something that I didn't? Any hints welcome, I would really like to get the Swift 4 version working on my machine.

**Comment by Ganzolo** [comment]
Xcode 9.2 + Swift 3.2, also does not work for me. :(

**Comment by klaas** [comment]
Did check again. I'm on macOS 10.13.4 (17E199) now and even the "Aerial.saver" that I compiled in January works now! :-)

**Comment by klaas** [comment]
I did a clean build, updated the Xcode project settings for Xcode 9.3 and removed a little Swift 4.1 warning.

Travis only supports "Xcode9.3beta" at the moment, but everything seems to work!

Now we are good to go and continue developing in Swift 4.1 ?!

**Comment by addisonwebb** [comment]
@klaas I also verified this morning that my fork compiled with Xcode 9.3 runs on macOS 10.13.4.

**Comment by glouel** [comment]
Closing this as we moved to Swift 4.2 with this PR : 
https://github.com/JohnCoates/Aerial/pull/501

**Pull request closed without merging**
