### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by NightRaider73**
CAP.

### CODE REVIEW

**Comment by glouel** [comment]
👍

**Comment by glouel** [comment]
Thanks !

**Comment by NightRaider73** [comment]
Is there any way you could give me direct edit access to the readme.md only?
It may save you some time so that I don't have to create a pull request every time.

**Comment by glouel** [comment]
I don't think I can do that, I'll double check. I know it's a bit of a pain to use PRs but I'm very thankful for your help on this !

**Pull request merged**
