### PR TITLE
Update issue_template.md

### PR DESCRIPTION
**Pull request by NightRaider73**
Just some CAPS

### CODE REVIEW

**Comment by glouel** [comment]
Awesome ! I think we could also add/update with what's in the readme's troubleshooting section. Feel like adding that ?

**Comment by NightRaider73** [comment]
Yep
I'm working on UI right now I will send you screen shots.

**Comment by NightRaider73** [comment]
screen shot 2018-10-18 at 1 01 06 pm
With this one the typo is: Second to Seconds.

**Comment by NightRaider73** [comment]
screen shot 2018-10-18 at 1 01 31 pm
I think "Show an extra message" sounds better:)

**Comment by NightRaider73** [comment]
screen shot 2018-10-18 at 1 01 45 pm

Maybe Cap.  the C in corner.

**Comment by NightRaider73** [comment]
screen shot 2018-10-18 at 1 03 22 pm

Change to: Sunset and Sunrise

**Comment by NightRaider73** [comment]
screen shot 2018-10-18 at 1 12 41 pm
I think you are suppose to start () with CAP. letters.

**Comment by glouel** [comment]
Good stuff thanks, I'll fix those tomorrow !

**Comment by NightRaider73** [comment]
screen shot 2018-10-18 at 2 09 28 pm
CAP. Language

**Comment by NightRaider73** [comment]
@glouel On the UI it says Aerial, maybe change it to Advanced
Just a suggestion
screen shot 2018-10-18 at 5 09 18 pm

**Pull request merged**
