### PR TITLE
Updated to and built with Swift 2.2

### PR DESCRIPTION
**Pull request by roonieone**
Updated #selector syntax and built with the latest stable version of Swift (2.2).

### CODE REVIEW

**Comment by lukehamburg** [comment]
Great! I noticed there are lots of unmerged PRs for this project. Last release (beta) was 8 months ago. Is development stalled? Why aren't these PRs getting any attention

**Comment by roonieone** [comment]
Huh. No idea. I hope not. But I have releases for Swift 2.2 and 3.0 on my fork now if anyone is interested in them.

**Comment by alistairmcmillan** [comment]
Not speaking for John here, it's his screensaver, but what benefit is there to compiling against Swift 2.2 or 3.0? Just curious.

Particularly 3.0 since it could change again before it's finally released.

**Comment by roonieone** [comment]
Compiling against 3.0 was just a fun project for myself, to learn some of the new syntax. Compiling against 2.2 has a tangible benefit if you have other screen savers that are compiled against 2.2. System Preferences has a weird bug that makes Swift screen savers crash and/or not work if you switch between two compiled against different versions of Swift (something about it trying to load the libraries for the wrong version) and that was happening to me.

**Comment by alistairmcmillan** [comment]
Trust me I know all about that bug. :) http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html It only loads the libraries for the first Swift screensaver and doesn't unload/reload for subsequent different Swift libraries. But it shouldn't cause crashes. You'll just get that `You cannot use the ... screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver.` error if you try to preview another one. They all should still actually work when they try to launch outside System Preferences.

And if you compile Aerial against 2.2 you'll only eliminate that error if all your other Swift screensavers are compiled against 2.2. What happens if people have other screensavers that are still compiled against 2.1, 2.0 or 1.0 even? They'll still bump into that error now and again.

**Comment by roonieone** [comment]
Well… All of the other Swift screen savers I use have actually been updated to 2.2. It may not benefit everyone if they're using screen savers built with outdated code, but there's certainly no harm in updating to 2.2 and since a lot of other developers seem to be updating their screen savers to the latest versions it's likely to be beneficial to quite a few people (myself included).

At this point choosing the version to compile against is arbitrary (if compiling against 2.1, what happens to people with screen savers compiled against 2.2, 2.0 or 1.0 even? -- and so on), so I don't think it hurts to update to the latest stable language release.

**Comment by alistairmcmillan** [comment]
The code has been updated to Swift 3.

**Pull request closed without merging**
