### PR TITLE
Expose Version Number

### PR DESCRIPTION
**Pull request by alistairmcmillan**
To make it easier to catch problems caused by people running older
versions.

Using the CFBundleVersion number to indicate 1.2 beta 5, based on the answers here http://stackoverflow.com/q/19726988/35794 and Apple's documentation here https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364

### CODE REVIEW

**Comment by rahmandon** [comment]
r03111068981@gmail.com

**Comment by JohnCoates** [comment]
Thanks, I'll be merging this soon!

**Comment by rayshan** [comment]
+1

**Comment by dokun1** [comment]
+1

**Comment by Saphiria** [comment]
@JohnCoates - Please merge this!

**Comment by glouel** [comment]
That feature was added as part of 
https://github.com/JohnCoates/Aerial/pull/501

**Pull request closed without merging**
