### PR TITLE
Optimization Translation Quality

### PR DESCRIPTION
**Pull request by jrthsr700tmax**
Optimization Traditional Chinese Translation Quality

### CODE REVIEW

**Comment by glouel** [comment]
Hi @jrthsr700tmax ! Sorry for not having answered earlier, I'll have a look at merging your changes this week. Many thanks!

**Comment by glouel** [comment]
Again, super sorry, merging this right now, this will be in beta12

**Comment by glouel** [comment]
@aitor do you know if we can propagate the changes made to the file in localize ?

**Comment by aitor** [comment]
@glouel Yep, although not ideal (@jrthsr700tmax please let me know if you want us to include you as chinese translator for the project), we should be able to push them to the service. I can check it out soon probably before the end of the week. Is that ok?

**Comment by glouel** [comment]
@aitor no hurries, I'll release beta 12 like this, I just want to make sure we don't lose this by merging back another language. 

Take your time and thank you very much !

**Pull request merged**
