### PR TITLE
Show extra descriptions on tvOS12 videos, Fade in/out for videos, Never Stream Videos options, & network fix

### PR DESCRIPTION
**Pull request by glouel**
Again this is a pretty large merge, sorry about that, but many of these things were linked to each other. As discussed in this issue https://github.com/JohnCoates/Aerial/issues/512, the primary purpose of this was to implement the displaying of the extended descriptions that are available with the tvOS 12 JSON that we are downloading. 

Changes : 
- Extra descriptions are now shown when available. Default to english with the option to localize (per my issue, there might be some displaying bugs in some non latin languages, but hard to get feedback from it, it will come soon enough when released I guess).
- Added fade in/out on the videos themselves
- Added preliminary detection for hardware acceleration support, and a better description based on latest findings (HEVC videos are encoded at Main10 profile which is not fully hardware accelerated pre 2017 Macs where the Intel iGPU is used)
- Don't redownload the tvOS 12 .tar file if already present in cache directory per this discussion 
https://github.com/JohnCoates/Aerial/issues/509
- Bypassing the VideoCache mecanism when the file is already fully cached. While it's a clever trick, it had a drawback of trying to assess the file duration, generating those error on console (and a 240 KB network request on every video) : 
`2018-10-01 20:17:53.633735+0200 AerialApp[10827:5184263] [] [20:17:53.634] curlh_lookupAndRetainRegisteredInfoForRequestIDOnQueue signalled err=-17374 (kFigCustomURLHandlerError_RequestingClientGone) (no requestingClient for this request) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-2282.15/Sources/DataIO/CustomURLHandling/FigCustomURLHandling.c:1223`
I think it also makes the video playback start slightly faster as a bonus. Haven't seen any network traffic since the fix.  
- Implemented a "Never Stream Videos" option. Only cached videos will be used if any. 
- Brought back check/uncheck all option below the list
- Some preparation for bringing back tvOS 10/11

I might also forget some other stuff. I tentatively bumped this to 1.4, not sure if this should end up being a prerelease or not, since people keep creating issues about things that were fixed already. At the same time, some may be displeased by the missing tvOS 10/11 videos if released as an update. So I'm of two minds about this one :)

### CODE REVIEW

**Comment by esetnik** [comment]
@glouel looks like it needs to be rebased off the latest master. Thanks!

**Comment by glouel** [comment]
Indeed working on fixing this ;)

**Comment by esetnik** [comment]
@glouel ok let me know if you need any help with it. I know you said you weren't too familiar with Github so just reach out if you get stuck.

**Comment by glouel** [comment]
Oh what a mess but I finally got it :)

**Comment by glouel** [comment]
@esetnik found a last minute bug in the issue thread, it's a quick fix but I'll do it tomorrow ;)

**Comment by glouel** [comment]
@esetnik Fixed the bug reported by @dVIAN13 here : https://github.com/JohnCoates/Aerial/issues/512#issuecomment-426366792

Good to go on my end.

**Comment by glouel** [comment]
I'll be temporarily pulling this, I expect to have a larger PR later today with a lot more features.

**Pull request closed without merging**
