### PR TITLE
Improved Russian translation

### PR DESCRIPTION
**Pull request by coffeeplanter**

### CODE REVIEW

**Review by Commensalism1997 — APPROVED** [review]

**Comment by glouel** [comment]
Hey @coffeeplanter & @Commensalism1997 

First thanks a lot for the PR, I'll be merging this later today in order to import the changes to Lokalise (the tool we use to generate those JSON in the end).

@coffeeplanter if possible would you mind being invited to the lokalise project for further changes ? I'll be adding the strings for the latest tvOS 15 videos there and it's much easier for me to export them this way and not override changes. 

Thanks in any case for the fixes !

**Comment by Commensalism1997** [comment]
very nice

**Comment by glouel** [comment]
This is finally merged for 3.0. Please reach out if you want access to Lokalise to translate the latest tvOS stuff, thanks !

**Comment by coffeeplanter** [comment]
@glouel, bonjour !
Thanks for the merge!
Yes, I'm ready to contribute to the translation on Localise. But I have never used this platform. )
By the way, what do you think about the user interface localization? I would like to have the Russian interface, for example. And ready to work on it.

**Comment by glouel** [comment]
Awesome ! Please send me an email to cwizou@gmail.com and I'll add you there, it's pretty easy to use, you just edit the keys there.

Regarding UI translation I'm hoping to get that started sometime soon yep, I'll let you know. Thanks again and sorry it took me so long to merge.

**Pull request merged**
