### PR TITLE
Updated to Swift 4.2 Syntax

### PR DESCRIPTION
**Pull request by AdrianBinDC**
- Removed empty Constants folder
- Update code to declare an Int, not an IndexDistance in Collection+Type.swift
- Updated Collection+Type.swift to random number generator Swift 4.2 syntax

### CODE REVIEW

**Comment by glouel** [comment]
Looks good, I think we should merge it straight after https://github.com/JohnCoates/Aerial/pull/521 (I should have my final changes there today).

**Comment by benjaminbogdanovic** [comment]
> Looks good, I think we should merge it straight after #521 (I should have my final changes there today).

Will #521 still be a pre-release/beta?

**Comment by glouel** [comment]
> Will #521 still be a pre-release/beta?

Hopefully not.

**Comment by benjaminbogdanovic** [comment]
> > Will #521 still be a pre-release/beta?
> 
> Hopefully not.

Great! Looking forward to it!

**Comment by AdrianBinDC** [comment]
[Anyone? :)](<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/8FhXc8w45aN32" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/teacher-anyone-ferris-bueller-8FhXc8w45aN32">via GIPHY</a></p>)

**Comment by AdrianBinDC** [comment]
[Any updates?](http://gph.is/1TqiIcG)

**Comment by glouel** [comment]
Hey, sorry about that, I was waiting on word from another maintainer before merging the big 1.4 feature push. I will probably end up merging all this today. Thanks for your contribution and hang on, it's coming I promise ;)

**Comment by glouel** [comment]
Again, thanks @AdrianBinDC for this and sorry for the delay !

**Pull request merged**
