### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by NightRaider73**

### CODE REVIEW

**Comment by glouel** [comment]
Thanks for rebasing. This looks good to me for the read me. As for the neon, maybe @SeanMSmith want to chime in? This looks good to me too so unless he manifests I’ll merge tomorrow for next build. Thanks !

**Comment by SeanMSmith** [comment]
Apple calls it "Screen Saver" (as you can see by looking in System Preferences or by getting info on the Aerial.saver package), and "Screen Saver" is perfectly correct English, so that's what we should be using.

Re "Sts", there are undoubtedly many words and abbreviations of which neither you nor I have yet heard. That's what a good dictionary is for! Try it. Select "Sts", right-click, and then select "Look Up “Sts”"; for more detail, click on "Open in Dictionary".

With a community project like this, my sense is that editors should probably take a light touch and refrain from correcting other writers' language in cases of mere stylistic preference, where there are no actual errors to be corrected or clear improvements in clarity to be made.

We should also be mindful of our busy and valiant project maintainers and refrain from putting them in the unenviable position of having to arbitrate between competing editors! @glouel certainly has enough to do as it is, and we should try to keep the noise-to-signal ratio as low as possible. :)

Also, as I wrote before, I'm really not wild about having to keep track of regional _preferences_ in cases where two or more variations are equally _correct_ and trying to enforce a standardized Aerial style guide. (Or should it be "standardised"?) That's making a lot of probably unnecessary work for an editor, especially when multiple editors are involved.

I'm getting confused enough as it is trying to keep track of these changes, and I'm the one who originally wrote these descriptions. So I submitted a new pull request of my own based on the v1.4.6beta1 master with the following changes:

1. I corrected "Ministy" and "Westmintser," thanks to @NightRaider73!
2. I changed "toward" to "towards" everywhere, as per @NightRaider73's original preference.
3. I spelled out "Saint" and "Saints" everywhere, to avoid all controversy over their abbreviations.
4. I corrected a typewriter apostrophe that none of us caught.

**Comment by NightRaider73** [comment]
@glouel Let me rebase the readme

**Comment by glouel** [comment]
> With a community project like this, my sense is that editors should probably take a light touch and refrain from correcting other writers' language in cases of mere stylistic preference, where there are no actual errors to be corrected or clear improvements in clarity to be made.

Yes, I think it's easy to go overboard with minor changes that have little impact and just take time to review. 

I also think that as we get more translations in, we need to be mindful of the work that will be put on those who will maintain those translations. 

@NightRaider73 thanks!

**Comment by NightRaider73** [comment]
@glouel Your welcome #639

**Pull request closed without merging**
