### PR TITLE
tvOS12 1080p + 4K, Swift 4.2, Video descriptions, fix Done button

### PR DESCRIPTION
**Pull request by glouel**
This is a followup to this PR https://github.com/JohnCoates/Aerial/pull/500 (originally based on @esetnik Feature/4k branch) with some extra changes/features : 
- updated to Swift 4.2/Xcode 10
- switch (in cache panel) for 1080p/4K
- Video description now shown (by default, configurable) bottom left of the screen for 10 seconds 
- added a version number at the bottom right of the panel

### CODE REVIEW

**Comment by joshlewis** [comment]
This seems like a huge win! I hope this can be merged in soon.

**Comment by esetnik** [comment]
@glouel if it's not too much work can you also investigate the failing tests? I'm seeing the last push to master was green https://travis-ci.org/JohnCoates/Aerial/builds/335603763.

```
3.46s$ git clone --depth=50 https://github.com/JohnCoates/Aerial.git JohnCoates/Aerial
Cloning into 'JohnCoates/Aerial'...
fatal: unable to access 'https://github.com/JohnCoates/Aerial.git/': SSL certificate problem: Invalid certificate chain
```

**Comment by esetnik** [comment]
@glouel seeing a few minor presentation issues on the labels in settings menu on your PR.

1. The titles should wrap when they are too wide for the container
2. The titles / subtitles should not be cut off. In this case `day` is being clipped for some reason.

screen shot 2018-09-24 at 9 35 20 pm

**Comment by kjg** [comment]
Are there any more failing tests? The  ‘Update Travis for Xcode 10’ commit and everything since has been green

**Comment by esetnik** [comment]
@kjg you're totally right. I missed the more recent commits. Looks like the test runner is working properly in recent commits. Thanks for pointing it out.

**Comment by glouel** [comment]
> @glouel seeing a few minor presentation issues on the labels in settings menu on your PR.
> 
> 1. The titles should wrap when they are too wide for the container
> 2. The titles / subtitles should not be cut off. In this case `day` is being clipped for some reason.
> 
> screen shot 2018-09-24 at 9 35 20 pm

1. Yeah I think the videos titles are longer, especially on space station
2. I probably messed with the Day/Night subtitle in IB

Part of the reason I messed with the Day/Night, is that as you know, there's no longer this distinction in the JSON. Some titles do include Day/Night but not all of them, so it's insufficient to categorize videos this way. 

Also I think the menu isn't really user friendly with the new JSON, it doesn't scale well (so much scrolling !) for two reasons : 
- There lot more videos (32 I think in the tvOS12 JSON)
- Most aren't grouped

Everything that isn't grouped is a space video... but there's also a space video titled China that gets grouped with the other China "Land" videos. 

So here's my thinking about this for this PR : 
- We get rid of the day/night subcategory for now, bringing everything one level down
- We make the menu larger (there's... space  :) )

It should fix both issues and make usage more comfortable.

In a second time, I see two options.
- Option 1 : We keep the code with no knowledge of the content of the JSON, so maybe we can decide to group all the solo videos in one subcategory to make it easier to scroll down
- Option 2 : We add a bit of knowledge, for each video ID that we know of, we can store if it's a day or night video, and if it's a space or land video. Using this we could reorganize that tree and allow back some features (there was one PR for showing day video by day, night by night that wouldn't work without that extra knowledge)

I'm afraid option 2 may irk Apple a bit.

Let me know what you think.

**Comment by glouel** [comment]
Agreed on all. I think you are right that since we already have the JSON hardcoded, it's not much more. We'll see that at a later point.

Short term, I removed the day subcategory for now and I've resized the list to be a bit larger, I'm a bit puzzled by the height thing, but I'm sure I'll find it soon.

I'll also push to this branch the H.264 support (see the last 2 issues opened about that for pre 2015 macs), I've added a popover to explain the video formats too. I'll commit as soon as I find that height thing !

**Comment by glouel** [comment]
So, I made the menu larger and moved the preview to the right, I think it look decent : 
capture d ecran 2018-09-25 a 17 59 46

I've also changed the 1080p/4K radios for a popup, and added a popover for clarity. We can probably make that help text clearer but that's a good start I think : 

capture d ecran 2018-09-25 a 18 00 42

**Pull request merged**
