### PR TITLE
Feature/multijson + Show extra descriptions on tvOS12 videos, Fade in/out for videos, Never Stream Videos options, & network fix

### PR DESCRIPTION
**Pull request by glouel**
This is the big one, includes everything from my previous PR 
https://github.com/JohnCoates/Aerial/pull/518 : 

- Extra descriptions are now shown when available. Default to english with the option to localize (per my issue, there might be some displaying bugs in some non latin languages, but hard to get feedback from it, it will come soon enough when released I guess).
- Added fade in/out on the videos themselves
- Added preliminary detection for hardware acceleration support, and a better description based on latest findings (HEVC videos are encoded at Main10 profile which is not fully hardware accelerated pre 2017 Macs where the Intel iGPU is used)
- Don't redownload the tvOS 12 .tar file if already present in cache directory per this discussion
#509
- Bypassing the VideoCache mecanism when the file is already fully cached. While it's a clever trick, it had a drawback of trying to assess the file duration, generating those error on console (and a 240 KB network request on every video) :
`2018-10-01 20:17:53.633735+0200 AerialApp[10827:5184263] [] [20:17:53.634] curlh_lookupAndRetainRegisteredInfoForRequestIDOnQueue signalled err=-17374 (kFigCustomURLHandlerError_RequestingClientGone) (no requestingClient for this request) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-2282.15/Sources/DataIO/CustomURLHandling/FigCustomURLHandling.c:1223`
I think it also makes the video playback start slightly faster as a bonus. Haven't seen any network traffic since the fix.
- Implemented a "Never Stream Videos" option. Only cached videos will be used if any.
- Brought back check/uncheck all option below the list
- Some preparation for bringing back tvOS 10/11

And : 

- Added new DownloadManager for queuing/managing simultaneous downloads (only used for JSONs so far)
- Added tvOS10 & tvOS11 videos (with list merging/blacklisted dupes, etc)
- Space videos are now grouped together for convenience
- Now providing day/night info for tvOS11/12 videos, the day/night indicator is back in the side column in preference pane 
- Moved `Video Format` to main pane, renamed to `Preferred Video Format`. Aerial will play the best available format based on preferred choice (if only 1080p H.264 is available and Preferred set to 4K, will still play the 1080p H.264)
- Added cached offline mode, will load from jsons in the cache directory before trying to fetch JSONs online 
- Fixed a bug where awakeFromNib was called dozens of times (once per TableCellView) at startup
- Added day/night mode based on specified sunrise and sunset times (new Time pane)
- Added Night Shift support to automatically detect sunrise and sunrise time (MacOS 10.12.4 and a supported Mac needed, see https://support.apple.com/en-us/HT207513)
- Added Light Mode/Dark Mode detection (MacOS 10.14 required) for day/night videos

This is a huge merge but it implements a lot of things that people kept requesting. As the UI was crowded already, I added a Time tab : 

capture d ecran 2018-10-05 a 17 43 05

@esetnik can you maybe have a quick look ? I'll merge and push a beta release later tonight if all looks good, it looks pretty solid here so far.

### CODE REVIEW

**Comment by glouel** [comment]
Put a beta build here too for testing : 
https://github.com/glouel/Aerial/releases/download/1.4beta10/Aerial.saver.zip

**Comment by dVIAN13** [comment]
@glouel , you are amazing! great work man.. hopefully you have a way for people to 'contribute' to your cause.. one thing I'd like to ask about this is for the time settings pane, could the time be dependent on time formatting set in the clock settings:? currently it is displaying in 24-hour, not AM/PM. other than that, the expanded settings are amazing.

**Comment by glouel** [comment]
Hehe thanks :) 

I thought the timepicker would be localized automatically, I'll have a look.

**Comment by esetnik** [comment]
@glouel I just built #521. Aside from 2 compiler warnings it's looking good to me.

A few points of feedback:
1. You don't need to close and open separate PRs. It's possible with Github to update an existing PR. All you need to do is push your commits to the same branch and the PR will automatically update. Not sure if you're aware of that but it might help.
2. I love that all the videos are available now, but the video selection screen is a bit confusing. It's unclear to me when I'm choosing the videos from the list whether I'm choosing 4k or 1080p content. Also what happens if I choose the "Prefer 4k" option? Maybe we should just indicate next to each video whether it's 1080p or 4k with a little tag in the list? Then we can just let people selectively choose which videos they want. If they want all 4k they can just unselect the 1080p ones. If they want all videos, they can select them all. I know there are a few overlaps (videos that have both 1080p and 4k versions), so we'd want to group those so they can uncheck the 1080p variant.
3. The text descriptions are blurry on my Retina MBP 2018. Maybe we need to do a scale factor on the text element?
4. I don't see any preview in settings page on #521 
screen shot 2018-10-05 at 12 00 22 pm
5. I don't think the HEVC acceleration detection is working on my system. I get a yellow indicator.
screen shot 2018-10-05 at 11 51 48 am
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Memory:	32 GB
  Boot ROM Version:	220.200.252.0.0 (iBridge: 16.16.375.0.0,0)

Intel UHD Graphics 630:

  Chipset Model:	Intel UHD Graphics 630
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x3e9b
  Revision ID:	0x0000
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal:	Supported, feature set macOS GPUFamily2 v1
Radeon Pro 560X:

  Chipset Model:	Radeon Pro 560X
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Dynamic, Max):	4096 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c2
  ROM Revision:	113-C980AL-060
  VBIOS Version:	113-C97501U-005
  EFI Driver Version:	01.01.060
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
```

**Comment by glouel** [comment]
@esetnik thanks for the quick check
1) Yeah I should have merged my other branch, good to know.

2) So right now it chooses the closest available, in order to make sure you always have access to all videos. If you pick 4K it will look for 1080pHEVC then 1080pH264, conversely, if you pick 1080pH264 and not available (only one HK video), you'll get 1080pHEVC for this one. I thought it was a better compromise than restricting strictly to what you want. I like the tag idea, I wanted to put two icons on the list (one to show if cached, one to show if 4K), I'll have a look at that. In the meantime, I wanted to add in the select menu below the list an option to select/deselect all 4K videos.

3) Oops, I'll have a look

4) You should try closing and reopening the pane, I think system preferences doesn't reload the user preferences which mess that first launch.

5) I added "may" as the detection state is uncertain right now, per discussion on a couple of threads. The API only allows to test for HEVC, not specifically HEVC Main10 profile  (so it answers yes on my iMac despite not being supported). I can make it green again if you think that's better, but leaving the may (I think the extra description I gave should be enough warning)

**Comment by glouel** [comment]
3) Just fixed ! I thought it was blurry too, should have thought about contentScale, nice catch thanks ;)
4) is annoying I agree, but not much we can do, it tripped me each time I added some new defaultvalues that weren't loaded
5) Agreed for 5 ! I think a dedicated issue where we explain current support is a good idea, linked in the readme

**Comment by glouel** [comment]
> I think also #336 can be closed since you reimplemented fading

Yep, I looked at that PR but it had some drawbacks, forced the old offline mode etc.

**Comment by glouel** [comment]
Ok, I added the "Check Only 4K" option as a temporary workaround for 2 until we put tags in the outlineView. 

I'll try having a look at the 24h / AM/PM localization for the Time pane.

**Comment by glouel** [comment]
(got inspired...) 
Test build here : 
https://github.com/glouel/Aerial/releases/download/1.4beta11/Aerial.saver.zip

**Comment by dVIAN13** [comment]
great! testing now. like I mentioned, here is how time is displayed

screen shot 2018-10-05 at 2 31 38 pm

**Comment by glouel** [comment]
> great! testing now. like I mentioned, here is how time is displayed
> 
> screen shot 2018-10-05 at 2 31 38 pm

Was it like that in previous beta ?? I thought I discarded my trials on that. The AM/PM is correct for you right ? Can you confirm that you can change those values (change, click done, reopen to see if they are persisted or not) ?

If so, it's just the display of the night shift ones then that I got to fix.

**Comment by dVIAN13** [comment]
@glouel correct.. the boxes were always correct. it was just the display on nightshift. :) not a big deal

**Comment by glouel** [comment]
Damn, I was trying to reproduce a bug on the boxes ! I'll fix that one tomorrow then, no problem.

**Comment by dVIAN13** [comment]
also(wait until tomorrow).. want to ask for clarification, the tag with the down arrow in the circle, what does that mean? downloaded, or not downloaded?

cache screen
screen shot 2018-10-05 at 2 43 45 pm

after switching back to main
screen shot 2018-10-05 at 2 43 53 pm

after closing/re-opening sys prefs
screen shot 2018-10-05 at 2 44 43 pm

**Comment by glouel** [comment]
Should mean not in cache for your preferred format (hopefully will make that a button to start download). I'll check that tomorrow too thanks !

**Comment by dVIAN13** [comment]
awesome, thanks! get some rest!

**Comment by SeanMSmith** [comment]
Re: Aerial 1.4 beta 11 (from [glouel/Aerial](https://github.com/glouel/Aerial))

With preferred video format set to 4K HEVC, Aerial 1.4b11 caches and plays the 1080p H.264 version of Dubai Night Two (http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_DB_D011_D009_SIGNCMP_v15_6Mbps.mov) instead of my already cached 4K HEVC version (https://sylvan.apple.com/Aerials/2x/Videos/DB_D011_C009_4K_SDR_HEVC.mov).

I see that the 4K HEVC version does not currently appear in the .json files for tvOS 10, 11, or 12, but it must have done so at some point, since [esetnik/Aerial](https://github.com/esetnik/Aerial) v1.3 cached it on 11 January 2018, and the 4K HEVC version is still on Apple's servers at the URL above.

(Based on a cursory check, this appears to be the only video for which Aerial 1.4b11 plays a 1080p version when I have a 4K version already cached.)

P.S. I opened an issue for this under the master fork, probably incorrectly, before thinking to look here. I'm afraid I'm not very used to GitHub.

**Comment by glouel** [comment]
(what a lovely mess, thanks sublime merge for getting me out of it 🤕 )

@dVIAN13 can you check this build and let me know if the AM/PM thing is fixed for you ?  
https://github.com/glouel/Aerial/releases/download/1.4beta12/Aerial.saver.zip

- Tentative fix for Night Shift dates not displayed correctly on AM/PM systems
- Fix garbled day/night icons on non retina displays
- Tentative contentScale on AVPlayerLayer (looks slightly sharper on retina displays)
- Fix video list cached indicators not getting refreshed when downloading new videos or changing preferred video format
- Added labels & legend for clarity
- Temporary changed the icon to a + for <10.12.2 compatibility

**Comment by snorbaard** [comment]
Hi Guys, 

Thought I’d at least chime in with the great work being done, which is HIGHLY appreciated.

Minor cosmetic notes

- On a non-retina display, the 4K labels look a smidge too low - as in, by a pixel


- Day/Night icons (on my non-Retina external display) in dark mode are black on dark grey. This is makes them difficult to see due to the low contrast difference.


- What does the tvOS12 localise option do? Perhaps a help widget to explain, if possible?

The video and description fades are gorgeous, by the way.

**Comment by dVIAN13** [comment]
@glouel, the AM/PM are there! 
screen shot 2018-10-06 at 12 34 01 pm

great job and continue to keep up the work. I really would like to buy you a coffee or beer(if that's your thing). Think about adding a support button for yourself to your git page or something!

**Comment by glouel** [comment]
> @glouel, the AM/PM are there!, thank you!
> screen shot 2018-10-06 at 12 34 01 pm
> 
> great job and continue to keep up the work. I really would like to buy you a coffee or beer(if that's your thing). Think about adding a support button for yourself to your git page or something!

🎉

Thanks for checking it out !n (and I'll think about it ;))

**Comment by glouel** [comment]
(still working on finishing up two more features that I really want to add for 1.4, single video download and download checked videos, hopefully by tomorrow)

**Comment by glouel** [comment]
So finally got the last bits I really wanted in : 
- If you haven't cached a video yet, there's now a + round button that you can click to individually download that video.
- In the menu below the video list, there are now two new options, Download Checked, Download All. 

You can select multiple videos individually (they will get queued, with the download indicator changing to a progress when it's actually downloading), same thing happen with Download Checked/All, it looks like this : 

capture d ecran 2018-10-08 a 10 07 44

As of right now, I set the queue to 1 at a time, although it can do more. I've tried to clean up a bit the Cache Panel a bit too, just cosmetic stuff. Finally, added a don't stream previews for those who never want any network traffic. 

Beta build here : 
https://github.com/glouel/Aerial/releases/download/1.4beta14/Aerial.saver.zip

Apart from bug fixes, I'm not touching this branch anymore featurewise, so hopefully we can finally merge this and release a 1.4.

**Comment by dVIAN13** [comment]
Working well! like the new enhancements. 2 suggestions? 

1) on my external monitors, the '4K' is still off center vertically(see screenshot) 
screen shot 2018-10-08 at 1 24 55 pm

2) possibly change the verbiage on the cache panel to match 'Never' stream videos(maybe change to 'Never stream previews') other than that, looks and functions great!

**Comment by glouel** [comment]
You're quick ;) 

Damn, about 1), indeed it's still offcenter here when compiled as a screensaver, yet it looks ok in Xcode and the test App 😱 I'll try to find a workaround tomorrow, thanks for catching that.

2) Would you keep what's inside the () ? It certainly would look cleaner without, I guess "Never stream previews" is self explanatory enough ?

**Comment by dVIAN13** [comment]
Okay. Thanks! Yeah, I agree, and maybe put it in a (?) help tooltip to explain better.

**Comment by SeanMSmith** [comment]
Guillaume, this all looks splendid, based on my very cursory check so far (apart, of course, from the repeating video issue I mentioned in https://github.com/JohnCoates/Aerial/issues/524).

Thank you for coding in the URL for the 4K version of Dubai Night Two!

One tiny thing that does bug me is the illiteracy of "Korean and Japan Night" [sic] in the accessibilityLabel in Apple's tvOS 12 JSON. Would you be willing, I wonder, to code a correction to "Korea and Japan Night"?

I also would like to be able to buy you a beer, and to buy one for Ethan as well, for your impressive work maintaining and improving Aerial!

**Comment by glouel** [comment]
So per the last feedback, a few tweaks :
 
capture d ecran 2018-10-09 a 12 07 34

- Fixed the 4K label alignment, made the list slightly larger, the queue image slightly larger too, and the progress bar shorter. Everything fits better with no more overlap. 
- If you've disabled the preview streaming, there's now a text mentioning it.Should be much clearer than the description I had put previously. 

capture d ecran 2018-10-09 a 12 08 59

- Dark Mode icons for day/night 🎉

capture d ecran 2018-10-09 a 12 09 24

- Shortened to Never stream previews (cf earlier) 
- Added a warning about file size, so people aren't surprised
- Added "Show in Finder" button

capture d ecran 2018-10-09 a 12 06 30

- Finally reduced the font size in the preview 😅

I also added a fix for the Korea thing @SeanMSmith mentioned. In the future, I think we could consider filling in basic descriptions about videos lacking them, to replace the "One, Two, Three" etc

beta build : https://github.com/glouel/Aerial/releases/download/1.4beta15/Aerial.saver.zip

> I also would like to be able to buy you a beer, and to buy one for Ethan as well, for your impressive work maintaining and improving Aerial!
I did add a link to my profile if that's your thing but don't feel like you have to. 


@esetnik, I think we should consider merging this now, any objection ?

**Comment by alxndrsbrwn** [comment]
Hi, this may have been answered, but some of these don't seem to work on my MBP. I'm running the dev beta of Mojave. Any thoughts on how I can resolve this? Thanks. See screen cap.
screenshot-12

**Comment by glouel** [comment]
> Hi, this may have been answered, but some of these don't seem to work on my MBP. I'm running the dev beta of Mojave. Any thoughts on how I can resolve this? Thanks. See screen cap.
Can you clarify what you mean by "some of these" ? Some videos ? Only some without the "4K" label ?

Off the top of my head, maybe you have some corrupted videos somehow (maybe a firewall that didn't allow the redirections ?). 

Use the "Show in Finder" button in cache Tab, look for a "b2-1.mov" for China 5. You can try opening it in Quicktime and see, filesize should be 116.2 MB. If you see .mov files that aren't way too small, try deleting them and redownloading anew ?

**Comment by alxndrsbrwn** [comment]
Yes, looks like it is some kind of issue with the downloads. I deleted the incomplete videos from the cache folder and tried to re-download them, but now I can see there's a connection error.
screenshot-13

**Comment by glouel** [comment]
Are you behind some kind of proxy or firewall ?

This is the link for that video : http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b2-1.mov

It should open and play in Safari, but note the many redirections (here it redirects to http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/b2-1.mov)

**Comment by dVIAN13** [comment]
@glouel: 4K tags fixed! amazing! also, can I just ask, if I have the videos cached already, the preview will display them, correct? however, if I don't have them cached, I will get the screen you have above stating 'video previews are disabled'?

**Comment by glouel** [comment]
> @glouel: 4K tags fixed! amazing! also, can I just ask, if I have the videos cached already, the preview will display them, correct? however, if I don't have them cached, I will get the screen you have above stating 'video previews are disabled'?

That's exactly it !

**Comment by alxndrsbrwn** [comment]
@glouel I shouldn't be, but switching networks seems to help. The ability to download them one at a time was a great idea for this type of issue. Thank you.

**Comment by glouel** [comment]
> @glouel I shouldn't be, but switching networks seems to help. The ability to download them one at a time was a great idea for this type of issue. Thank you.

Great. Maybe as a future feature we could add some extra checks for that, I assume you saw .mov that were a few KB only, or something like that ?

**Comment by alxndrsbrwn** [comment]
@glouel Yes, small file sizes and the preview image in Finder was incomplete. They also didn’t run in QT.

**Comment by SeanMSmith** [comment]
Guillaume, for the sake of consistency, I would suggest standardizing capitalization:

1. In the Main panel, change "Preferred Video Format" to "Preferred video format"
2. In the Main panel, change "Play Different Aerial On Each Display" to "Play different Aerial [_or_ aerial] on each display", thereby matching the capitalization on the other checkbox descriptions
3. In the Time panel, change all four occurrences of "MacOS" to "macOS"
4. In the Cache panel, change "Cache Aerials As They Play" to "Cache Aerials [_or_ aerials] as they play"

Finally, in the Time panel, remove the spurious space before the colon in "Aerial can display day and night videos based on time :" (changing "time :" to "time:").

I'm inclined to think that the current error message "Video preview streaming is disabled" is sufficient, since the message should appear only if the user does not have the video cached.

(Speaking as a writer and editor, I have to say that your English seems better than that of most of my fellow native English speakers!)

**Comment by glouel** [comment]
Awesome, I'll fix those consistency things tomorrow, thanks !

**Comment by glouel** [comment]
> 1. In the Main panel, change "Preferred Video Format" to "Preferred video format"
> 4. In the Cache panel, change "Cache Aerials As They Play" to "Cache Aerials [_or_ aerials] as they play"

So, I went and had a look at english MacOS, indeed the rules seems to be : 
1) Labels and checkbox : only first word is capitalized
2) Window titles, Buttons and Tab headers and dropdown menus : capitalize every major word (baring pronouns)

So I adjusted the checkboxes per your recommandations, and kept the buttons as they are. Also made a judgment call on keeping "Visit Project Page" as is, it's technically a button... although it looks like a label :)

I also changed "10 seconds" to "10 Seconds" in the dropdown, and on Cache panel went for "Total progress" and "Current video" (I strongly considered adding ":" at the end of those ?). I think that's pretty much it (and fixed the space before double ponctuation, french habit sorry !)

Funnily enough, on french MacOS the capitalization rules aren't the same : 
1) That one stands
2) Only first word are capitalized : 

capture d ecran 2018-10-09 a 12 06 30

(See, title, buttons, dropdown) 
Except... 
capture d ecran 2018-10-10 a 10 55 51

"Préférences Clavier" (Keyboard Preferences) somehow gets the reverse treatment. Localization consistency 😅

> 2. In the Main panel, change "Play Different Aerial On Each Display" to "Play different Aerial [_or_ aerial] on each display", thereby matching the capitalization on the other checkbox descriptions

I went with Aerial(s)... It's /Aerials/ in the new urls so that swayed it for me. 

> 3. In the Time panel, change all four occurrences of "MacOS" to "macOS"

I have to say that one physically hurts, but changed those too.

> I'm inclined to think that the current error message "Video preview streaming is disabled" is sufficient, since the message should appear only if the user does not have the video cached.

The default for "Never stream previews" is off, so you'd have to explicitly check that box to see that message. So, yeah, should be straightforward enough.

Question for you, would "Preview streaming is disabled" be grammatically better/less of a "heavy turn of phrase" as we'd say in french ?

> (Speaking as a writer and editor, I have to say that your English seems better than that of most of my fellow native English speakers!)

Thanks and many thanks for your feedback !

beta build here : 
https://github.com/glouel/Aerial/releases/download/1.4beta16/Aerial.saver.zip

(and many thanks too to @dVIAN13 too for your testing, feedback and everything else)

**Comment by SeanMSmith** [comment]
Grammatically, "Preview streaming is disabled" and "Video preview streaming is disabled" are equally correct, but I do think the longer form is needlessly wordy; "Preview streaming is disabled" is just as clear and better for being shorter.

Personally, I too dislike "macOS"; medial capitals (aka "InterCaps") in English, especially when the first letter is uncapitalized, strike me as silly and pretentious. Alas, marketing creatures are addicted to them.

"Check Only Cached" and "Check Cached Only" (likewise "Check Only 4K" and "Check 4K Only") are equally correct grammatically, and sound equally good to me. (The only variation I would avoid is "Only Check Cached", where the "only" modifies "check" rather than "cached".)

Thank you for your most refreshing attention to detail!

**Comment by glouel** [comment]
Thanks for all this, I shortened to "Preview streaming is disabled" (and couldn't agree more on intercaps !). 

@esetnik any objection on merging ?

**Comment by glouel** [comment]
@SeanMSmith can you check 
https://github.com/glouel/Aerial/releases/download/1.4beta17/Aerial.saver.zip

I've implemented a better random through playlist, this should solve your issues (see my comment there https://github.com/JohnCoates/Aerial/issues/524#issuecomment-428871536 ). This also fixes a couple of startup bugs I saw on first launch experience.

**Pull request merged**
