### PR TITLE
Some more space videos added to the community file (spanish)

### PR DESCRIPTION
**Pull request by aitor**
cf. https://github.com/JohnCoates/Aerial/pull/713#issuecomment-45976065

### CODE REVIEW

**Comment by glouel** [comment]
@aitor thank you so much ! Merging this !

**Comment by aitor** [comment]
@glouel Here they are. 

If more languages are going to be maintained I'd strongly suggest to adapt a more organized approached to the internationalization. Most specialized SaaS tools offer a free plan for open source projects:

https://docs.transifex.com/projects/open-source-project
https://phraseapp.com/pricing
https://lokalise.co/pricing/

This way we'll all manage the same keys and will be easy to coordinate new releases. 

I'd happily help to integrate any of these tools in the project if needed. 👍

**Comment by glouel** [comment]
Great suggestion, this would definitely make things a LOT more manageable !

I never looked into those so if you have a suggestion about a particular solution, let me know. Could we integrate the JSON format as is or would it need changes ? 

Side note, I hope you won't mind but I probably won't be posting beta 4 with your changes today, as I'm trying to fix an auto update bug before pushing beta 4. Thanks again !

**Comment by glouel** [comment]
@aitor so took some time but I finally released beta4 with your file, as I'm working with the new format thing ;) beta 4 here : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.7beta4/Aerial.saver.zip

**Pull request merged**
