### PR TITLE
Brew Cask Update????

### PR DESCRIPTION
**Pull request by NightRaider73**
I am going to test before I change it again:)'
Edit: Brew is updated for 1.4.5:)
Also can you fix Travis?

### CODE REVIEW

**Comment by NightRaider73** [comment]
@glouel Do you like the Featured on 9to5mac Section?

**Comment by glouel** [comment]
I'm currently away for work but will get to it soon

**Comment by NightRaider73** [comment]
Just read the PR I added one

**Comment by NightRaider73** [comment]
Sorry to bother you, when will you be coming back?

**Comment by glouel** [comment]
Later this week.

**Comment by NightRaider73** [comment]
@glouel Please merge this I removed the 9to5mac sections so that the only changed part is the 1.4.5, which is correct

**Comment by glouel** [comment]
Merged and will look at the other stuff later. Will be back on friday ;)

**Comment by NightRaider73** [comment]
I will try not to bother you until Friday.
Thanks

**Pull request merged**
