### PR TITLE
New Community JSON format

### PR DESCRIPTION
**Pull request by aitor**
Hi @glouel,

I've ported the current Community strings to a new proposed JSON format. This format would make easier to integrate the strings with automated translation workflows (cf. JohnCoates/Aerial#715).

I've seen the work to look up the translations is done in `PoiStringProvider` but before we go into that, I'd like to have your approval on this new format. The main ideas:

- The video IDs are used as main keys. This provides the SaaS i18n services a unique, nestable, directly lookable key that is common for every language. 
- The keys are nestable. This gives us the possibility to specify `pointsOfInterest` keys for some videos, and if needed any other key in the same namespace.
- I've removed `version` (with this workflow we have the git and SaaS versioning at our disposal and AFAIK it hasn't been used) and `language` (the file itself defines the language) attributes.

With this new key oriented JSON we can easily import the file in any i18n SaaS service that will provide UI and multiple tools to translate the content, and options to collaborate with anyone that wants to help  to translate (example from Lokalise):

cleanshot 2019-02-05 at 20 30 40

All the services I mentioned support a Push/Pull model, so once a translator has updated a translation we could simply "pull" the last versions of all the files from the CLI (again example from Lokalise):

```
> lokalise --config lokalise.cfg  d --type json --unzip_to Resources/Community --bundle_structure %LANG_ISO%.%FORMAT%           

Requesting...
Remote https://s3-eu-west-1.amazonaws.com/lokalise-assets/files/export/526621525c507/a3f70/Aerial-locale.zip... OK
Local Aerial-locale.zip... OK
Unzipped Resources/Community, Resources/Community/en.json, Resources/Community/fr.json, Resources/Community/es.json OK
```
So from the point of view of code/resources loading everything is still local and no SaaS is pinged or referenced, preventing vendor-locking.

Let me know what you think.

PS: Do you have any way to test `PoiStringProvider`?. It would be great to test the new format.

### CODE REVIEW

**Comment by glouel** [comment]
> Hi @glouel,
> 
> I've ported the current Community strings to a new proposed JSON format. This format would make easier to integrate the strings with automated translation workflows (cf. #715).

First, thanks a lot for looking into this @aitor ! I'm a bit under the weather right now so I'll keep this short and hopefully have a more throrough look tommorrow.  

> I've seen the work to look up the translations is done in `PoiStringProvider` but before we go into that, I'd like to have your approval on this new format. The main ideas:
> 
> * The video IDs are used as main keys. This provides the SaaS i18n services a unique, nestable, directly lookable key that is common for every language.

This sounds much better indeed ! FYI the JSON structure was based on the one used by Apple.

This is more of a tooling thing probably, but because Apple changes the IDs of videos from time to time, we'll need to be able to do a couple of things hopefully to all the JSONs simultaneously. One is, renaming a key, second is, changing some subkeys : 

```
"40": "Passing the Gherkin in the City of London, on the right",
```
In this, hopefully we can change 40 to 30 on all the JSONs. See what I mean ?

> * The keys are nestable. This gives us the possibility to specify `pointsOfInterest` keys for some videos, and if needed any other key in the same namespace.

Sounds good. 

> * I've removed `version` (with this workflow we have the git and SaaS versioning at our disposal and AFAIK it hasn't been used) and `language` (the file itself defines the language) attributes.

Agreed

> With this new key oriented JSON we can easily import the file in any i18n SaaS service that will provide UI and multiple tools to translate the content, and options to collaborate with anyone that wants to help to translate (example from Lokalise):
> 
> cleanshot 2019-02-05 at 20 30 40
> 
> All the services I mentioned support a Push/Pull model, so once a translator has updated a translation we could simply "pull" the last versions of all the files from the CLI (again example from Lokalise):
> 
> ```
> > lokalise --config lokalise.cfg  d --type json --unzip_to Resources/Community --bundle_structure %LANG_ISO%.%FORMAT%           
> 
> Requesting...
> Remote https://s3-eu-west-1.amazonaws.com/lokalise-assets/files/export/526621525c507/a3f70/Aerial-locale.zip... OK
> Local Aerial-locale.zip... OK
> Unzipped Resources/Community, Resources/Community/en.json, Resources/Community/fr.json, Resources/Community/es.json OK
> ```
> So from the point of view of code/resources loading everything is still local and no SaaS is pinged or referenced, preventing vendor-locking.
> 
> Let me know what you think.

I have to say this does look pretty good indeed and the changes are relatively small to the format so it should be trivial to modify PoiStringProvider. Unless I'm missing something, I see no drawback to moving to that format (there's the tooling/modifying key thing I mentioned above I guess).

Thanks a lot for looking into it !

> PS: Do you have any way to test `PoiStringProvider`?. It would be great to test the new format.

You mean making the changes to it ? Should be quite easy, I'll have a look tomorrow if I start feeling a bit better. The whole thing looks a bit convoluted but it's actually pretty simple.

**Comment by aitor** [comment]
> we'll need to be able to do a couple of things hopefully to all the JSONs simultaneously.

Yep, it's perfectly possible. The exact process is as just said tooling-dependant and varies depending on what SaaS we use but basically you'll pick the affected key and "rename" it. All the JSON will be regenerated on the next "pull" to include the new key, while keeping the translations already made for them.

> You mean making the changes to it?

I was talking about unit testing the class, a proper test to be sure the new format is applied correctly. That way I could more easily make the changes and help you. (BTW: hope you get better soon, no hurry at all to implement this).

**Comment by glouel** [comment]
> > we'll need to be able to do a couple of things hopefully to all the JSONs simultaneously.
> 
> Yep, it's perfectly possible. The exact process is, as you said, tooling-dependant and varies depending on what SaaS we use but basically you'll pick the affected key and "rename" it. All the JSON will be regenerated on the next "pull" to include the new key, while keeping the translations already made for them.

Perfect thanks for clarification. This will be a great help. 

> > You mean making the changes to it?
> 
> I was talking about unit testing the class, a proper test to be sure the new format is applied correctly. That way I could more easily make the changes and help you. 

There's not much testing in the code right now, I'll give a shot to the new implementation in a branch. If the JSON is malformed you instantly crash so it's an easy debug ;) 

> (BTW: hope you get better soon, no hurry at all to implement this).

Thanks, not a 100% but getting there !

**Comment by aitor** [comment]
> There's not much testing in the code right now, I'll give a shot to the new implementation in a branch.

@glouel Super, let me know then when the new format is adopted. I can then jump back in and finish establishing the workflow for the i18n process and porting the current translations to it. And let me know if I can help with porting the `PoiStringProvider` to the new format.

**Comment by glouel** [comment]
Porting to the new format was really easy, just changed a few lines, didn't deserve a branch, you can see the change here  : https://github.com/glouel/Aerial/commit/26eb394d8c65de194334295956df78f7b3cc3454#diff-7dd02df370ab6fa9a5ab9ac98a351ffe

So I made a test build with just the new en.json bundled, you can find it here : 
https://github.com/glouel/Aerial/releases/tag/v1.4.7test8

I also attached my "old format" fr.json that was in progress if you want to play with it.

I don't know if you are aware as this is not really documented, but if you want to test a new format file, you can create a `locale` folder in your Aerial cache folder and put the json here, it will get loaded instead of the one in the bundle if there. 

Let me know how it goes on your end ! As for the workflow, tooling and stuff, let me know if I need to create an account somewhere. I'll trust your judgment on the best one to use. Thanks !

**Pull request merged**
