### PR TITLE
Add option to show the name (location) label in the bottom right corner of the screen saver.

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by ohayon** [comment]
Any chance we can get this merged in?

**Comment by kevinawoo** [comment]
I've forked this and been able to have it show up on screensaver

Below are some images thats tagged with `Greenland` on the bottom left.

image 2017-07-06 at 4 43 14 pm
image 2017-07-06 at 4 43 27 pm
image 2017-07-06 at 4 41 34 pm

**Comment by mgguinne** [comment]
Nice job! Be great to have this in the main version

**Comment by MichaelDimmitt** [comment]
@kevinawoo's fork worked on my machine. 

Because Aerial.saver was correctly compiled.
@ohayon's fork did not work for my machine. 
If the code were updated id give it a thumbsup!
But I don't have any authority. Just another programmer saying thanks. 
@ohayon @kevinawoo @alistairmcmillan

**Comment by kevinawoo** [comment]
I made a forked release for those that can't or are too lazy to compile it.
https://github.com/kevinawoo/Aerial/releases/tag/v1.3-location-lables

You can download it here https://github.com/kevinawoo/Aerial/releases/download/v1.3-location-lables/Aerial.v1.3-location-labels.zip

**Comment by MichaelDimmitt** [comment]
@kevinawoo, nice. If you want to see the label with aerial on your desktop;
I added the Aerial.saver with the label fix into my Aerial_Desktop application. 
https://github.com/MichaelDimmitt/aerial_desktop

**Comment by MichaelDimmitt** [comment]
In case you guys want to quickly update your code. I can attest labels will still work. 
@kevinawoo @ohayon 
```git remote add upstream https://github.com/whoever/whatever.git;
git pull upstream master;
git rebase upstream/master;
git push -f origin master;```

**Comment by MichaelDimmitt** [comment]
@ohayon, so I thought that I would have to increase label size for my grandma who has macular degeneration. Right away she whipped out "magnifying glass" on her iPhone. 😂  

She preferred the label at that size because it did not take away from the content and only needed to look up the location label when unaware what location she was viewing.
So far I have gotten six people to download @kevinawoo's Aerial.saver all reviews have been positive about label size. 💯

**Comment by jrwesolo** [comment]
@JohnCoates Any thoughts on this? It seems like a great feature.

**Comment by ohayon** [comment]
Feel free to install from my fork here: https://github.com/ohayon/Aerial. I can also build a release so it's easier if that's helpful. 🚀

**Comment by travi** [comment]
@ohayon any chance your fork is brew installable?

**Comment by ohayon** [comment]
Hey @travi - it isnt currently, but I can make that happen for sure!

**Comment by travi** [comment]
that would be huge. the ease of installing the old version with brew is the whole reason i don't yet use your fork.

**Comment by MichaelDimmitt** [comment]
@ohayon, @kevinawoo 
You can script location labels to be enabled by default in bash.
```bash 
defaults -currentHost read com.JohnCoates.Aerial
shouldShowNameLabel = 1;
```
bottom of the result had the key of interest 😋

## turn labels on:
```bash
defaults -currentHost write com.JohnCoates.Aerial shouldShowNameLabel 1
```
## turn labels off:
```bash
defaults -currentHost write com.JohnCoates.Aerial shouldShowNameLabel 1
```

**Comment by glouel** [comment]
So this has been reimplemented in 1.4 with the extra descriptions provided by tvOS 12 with the supplied strings bundle that comes in the .tar with the json. Thanks for the contribution though!

**Pull request closed without merging**
