### PR TITLE
copyright disclaimer

### PR DESCRIPTION
**Pull request by rduan8**
added all rights reserved

### CODE REVIEW

**Comment by JohnCoates** [comment]
Thanks @rduan8, but the official MIT License here https://opensource.org/licenses/MIT doesn't include that. Any reason why this is significant to go against the official version?

**Comment by Markyt1977** [comment]
mark tegeda

**Comment by tnViking** [comment]
There is no need for *All rights reserved* in a MIT license, because it explicitly gives permission, “without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sub license, and/or sell copies of the Software.” The only condition is that the full copyright notice (which declares no warranty or liability) be included. Work released under the MIT license can be used for anything, including commercial and proprietary software.

**Comment by alistairmcmillan** [comment]
No reply from @rduan8 for a few months. Closing.

**Pull request closed without merging**
