### PR TITLE
My rebase

### PR DESCRIPTION
**Pull request by NightRaider73**

### CODE REVIEW

**Comment by NightRaider73** [comment]
Fixed it

**Comment by NightRaider73** [comment]
@glouel I rebased here.
But my other one where it had the delete auto update was correct because, technically it doesn't auto update it, you still have to type something for it to update.  It means it updates by itself

**Comment by NightRaider73** [comment]
But I agree kinda

**Comment by glouel** [comment]
Yeah, it's still easier and people that use package manager are used to that kind of thing, I have a version check branch somewhere but not ready (and will not auto update but will let you know when an update is here). Thanks !

**Pull request merged**
