### PR TITLE
Hebrew translations. עושר ואושר!

### PR DESCRIPTION
**Pull request by aitor**
Kudos to @kaaspad for this!!

### CODE REVIEW

**Comment by glouel** [comment]
Perfect timing ! Kudos to @kaaspad, hopefully we handle RTL text ok enough, we'll see ! Will merge and get a beta out today.

**Comment by glouel** [comment]
I actually thought the export was wrong as xcode literally show the whole json line inverted just for the pois (but not the other lines, that took me a while) ! I do think it's ok though in the end, maybe @kaaspad can have a look :

צילום מסך 2019-04-11 ב-16 57 01

Looks similar to lokalise and xcode !

**Comment by aitor** [comment]
Given it's only inverting certain subkeys I guess that's probably a bug in XCode file renderer, and not some kind of hebrew editing convention. 

CleanShot 2019-04-11 at 17 12 40

Visual Studio Code renders the file "correctly".

CleanShot 2019-04-11 at 17 13 09

**Comment by glouel** [comment]
I guess I shouldn't be surprised by Xcode bugs but that one really threw me off for a minute :)

**Pull request merged**
